# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

language: cpp

os: linux
dist: focal

services:
  - docker

jobs:
  include:
    - stage: build
      arch: amd64
      script:
        - |
          export TZ=Asia/Shanghai
          IMAGE_NAME="kvrocks/kvrocks"
          IMAGE_TAG="nightly-$(date -d @$(git show -s --format=%ct $TRAVIS_COMMIT) "+%Y%m%d")-${TRAVIS_COMMIT:0:7}-$TRAVIS_CPU_ARCH"
          echo building $IMAGE_NAME:$IMAGE_TAG
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BRANCH" == "unstable" ]]; then
            echo pushing $IMAGE_NAME:$IMAGE_TAG
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
            docker push $IMAGE_NAME:$IMAGE_TAG
            docker logout
          fi
    - arch: arm64
      script:
        - |
          export TZ=Asia/Shanghai
          IMAGE_NAME="kvrocks/kvrocks"
          IMAGE_TAG="nightly-$(date -d @$(git show -s --format=%ct $TRAVIS_COMMIT) "+%Y%m%d")-${TRAVIS_COMMIT:0:7}-$TRAVIS_CPU_ARCH"
          echo building $IMAGE_NAME:$IMAGE_TAG
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BRANCH" == "unstable" ]]; then
            echo pushing $IMAGE_NAME:$IMAGE_TAG
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
            docker push $IMAGE_NAME:$IMAGE_TAG
            docker logout
          fi
    - stage: push
      script:
        - |
          export TZ=Asia/Shanghai
          IMAGE_NAME="kvrocks/kvrocks"
          IMAGE_TAG="nightly-$(date -d @$(git show -s --format=%ct $TRAVIS_COMMIT) "+%Y%m%d")-${TRAVIS_COMMIT:0:7}"
          if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BRANCH" == "unstable" ]]; then
            echo pushing $IMAGE_NAME:$IMAGE_TAG
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
            docker manifest create $IMAGE_NAME:$IMAGE_TAG --amend $IMAGE_NAME:$IMAGE_TAG-amd64 --amend $IMAGE_NAME:$IMAGE_TAG-arm64
            docker manifest inspect $IMAGE_NAME:$IMAGE_TAG
            docker manifest push $IMAGE_NAME:$IMAGE_TAG
            docker manifest create $IMAGE_NAME:nightly --amend $IMAGE_NAME:$IMAGE_TAG-amd64 --amend $IMAGE_NAME:$IMAGE_TAG-arm64
            docker manifest push $IMAGE_NAME:nightly
            docker logout
          fi

env:
  global:
  - secure: a3Arhq40+YpulNRwAUAHTMwfKuc6kJqPFkP/2fex5UwkkGeeeBTmOTT9Y4BSXr1z2SAjS6HGSZ3fzC+2uz0JDX67F9Ssk8XzJiXlPkqu/xcQI+YVHxnW+xBCAdcJ/zO/vcPOzIh2fvUOzQRC0JDDYtmVFNdI0XnYf5thtcZBZGobVS3D2yXW8BsFMeH0mWeYzhWFdzt8tcQUU+abPWKrAZljNFk93Nxal5xadtYrMkM4C4OsGqeLz96HOObU9jcnFJVokLP4zUxt+uohLd2RIeec4E/IhJE0DCtvxdN/pF3vTL14knE/iNlsE1ogDZDVmPX1UK+mJn+Np7OEhMQqj/p81kYEgelJwYeaW+CFvn55CyM9ES3m9B/V1Z75dolHdvIhvsvIP8irbPLuYpa6XP1bD5aFZv78SbJso68XHPy8yGZCMyRxJnI5G57xvMFScnQ490PP51Jfr3bbskQg8f6QWDLMG/TdyP+aHGCLZ/cPCj6sL0HA7xbHtRs988LM7i08v9FscX5pYZ22aSp/VyFfsFb71rd6bi2yNX6FiP/2PcAq7WQ2xfcnsgvGRuZvJu8buWLCDlzIC4GqWgJQ+o6Ws1RVHq4krnNhhBlMXVdQdTJ/7Jpge1aABjGMhQlF/Urw+Z7ArWAnftW+PxMR6Pr6Xc2CzdlBmTR/53/IwOA=
  - secure: PdNRIWbedzoRWy1JUgHyjvW6dXjcaUChXDyIfZFtZjojBRrNoIGag0Cm/qEQIG4Np6TaQGDJdVMYOT0q7bYIf2/vmIpc1sIn2Ez1YoOS94cSOHUHORCohc1D53u4B5rrW15ecGhOncjBqW/j0WV7fhE4Nl6CvLOCaBVuFaMOKDNS3L/BPwu41n4R3CT/bwdKFGwg8gJN06+zRBZYFMrzPi5mfxWLB/C+H2KZUmoa5shZ1kwPkH1mIqTrj+TEy+U0woTiIHOoxsmHzkC46f8FPMmWXzhn3QZiWe+m9TChZltB20tPTfc+2m8M1pMjBs1bQW72tULLJMVYo5YQxCkeYNEd6Xst99X4y/fGKy22nABEDrh356TE4voJts2fyi3SO8qExNpVPXui+8iy0icU8MRb0s5RIeACqIamFOaqQ9Pow2Om5xwsk6x4F45n+5ec4LQceV48cd0YrhWUMZDDMMwSd+vNIf9hIzxhXmj5I76nGSHzjDxHBMaG3aUCD6S5D2HmrVrKXeut+89IBbuL+nv9jGJPCtJM/YUyVnnHNOMqbprZzsIq1/u/cKB9t2AbVTJlu9G4PfqX61Jy3s7PDN9n4IGzwZ0V3VC85QffoiEs3j/8KvtfF6xSxB12gpaGkg+24nt54TmTh40QbkTe/Nl35YruwV7+0Pze1hfCP0o=
